flags:
  pandoc:
    trypandoc: false
    embed_data_files: true
    network-uri: true
  pandoc-citeproc:
    bibutils: true
    embed_data_files: true
    unicode_collation: false
    test_citeproc: false
    debug: false
packages:
- '.'
extra-deps:
- pandoc-citeproc-0.14.3.1
- skylighting-0.7.0.2
- skylighting-core-0.7.0.2
- ansi-terminal-0.8.0.2
- tasty-1.0.1.1
- test-framework-0.8.2.0
- pandoc-types-1.17.4.2
- cmark-gfm-0.1.3
- hslua-module-text-0.1.2.1
- texmath-0.11
ghc-options:
   "$locals": -fhide-source-paths -XNoImplicitPrelude
resolver: lts-10.10
